#language: java
language: minimal
cache:
  directories:
    - $HOME/.jabba/
matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      #jdk:
      #  - openjdk8
      env:
        - JDK="adopt@1.8"
        - TRAVIS_DIST_NAME="xenial"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      #jdk:
      #  - openjdk11
      env:
        - JDK="openjdk@1.11"
        - TRAVIS_DIST_NAME="xenial"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      #jdk:
      #  - openjdk13
      env:
        - JDK="openjdk@1.13"
        - TRAVIS_DIST_NAME="xenial"
    - name: "MacOS JDK8"
      os: osx
      osx_image: xcode10.1
      #jdk:
      #  - openjdk8
      env:
        - JDK="adopt@1.8"
        - TRAVIS_DIST_NAME="osx10"
    - name: "MacOS JDK11"
      os: osx
      osx_image: xcode10.1
      #jdk:
      #  - openjdk11
      env:
        - JDK="openjdk@1.11"
        - TRAVIS_DIST_NAME="osx10"
    - name: "MacOS JDK13"
      os: osx
      osx_image: xcode10.1
      #jdk:
      #  - openjdk13
      env:
        - JDK="openjdk@1.13"
        - TRAVIS_DIST_NAME="osx10"
    - name: "Windows JDK8"
      os: windows
      env:
        - JDK="1.8"
        - TRAVIS_DIST_NAME="win"
    - name: "Windows JDK11"
      os: windows
      env:
        - JDK="openjdk@1.11"
        - TRAVIS_DIST_NAME="win"
    - name: "Windows JDK13"
      os: windows
      env:
        - JDK="openjdk@1.13"
        - TRAVIS_DIST_NAME="win"
env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    
before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait brew update; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - git clone https://github.com/Funz/funz-core
  - cd funz-core
  - ant dist
  - cd ..
  - git clone https://github.com/Funz/funz-client
  - cd funz-client
  - ANT_OPTS="-Xmx6G -Xss1G" ant dist-test
  - cd ..
  - cd $WD

before_script:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  #- if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --allow-unauthenticated; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended --allow-unauthenticated -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HOMEBREW_NO_AUTO_UPDATE=1; rm -f '/usr/local/include/c++'; brew install r; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then RH=`ls /usr/local/Cellar/r/`; echo `ls /usr/local/Cellar/r/$RH/bin`; export PATH=$PATH:/usr/local/Cellar/r/$RH/bin; fi
  #- if [[ "$TRAVIS_OSX_IMAGE" == "xcode9.3" ]]; then brew uninstall --ignore-dependencies --force python; brew install python3; fi # to get python3 instead of 2 -> ok.py test working
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install r -y; fi
script: 
  - ant test

after_success:
  - ant coverage
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../funz-calculator.zip ./*
  - cd ..

deploy:
  provider: releases
  name: funz-calculator
  api_key:
    secure: InNIkp1ZqgaV1vKPpNMVVQe7nwyTFoxPiiPVXombyloA2402OSyX2EotPUpz5madYCqFloKS9hxbXuBJ8LCPtDc6J9yQrL783DtGMR8TitPfHcb3KN5E6fGyyowW1VbhNPW0ErE7hfjZf67uwf9JJfgU2rvGWwOiE+cZsR2EP4C/eWw8BzNEBzpD9fxzidWA11wz8IEpVWjt1fkqNJlLBPp4i8kwNPM2vY97jSvuSq412ZTCwclcZnyMk2Cn2W93X/4CG2OF+EYyyCKSnOY+sVIXmwQyrTSo8nCE7TiWNk7PMH23Q1d2vBVXvZCbO8CLdNqGTo07Z1v0sBTtJII5W+v40i6lIemEn7Qi2x0xc/csQZUsNlqW41cdsHYgdr6D9fVw3oXEwPP2gQHs7UQGEdWaAye1DAx4gKuIS3EK6D0idrwsiUb25ZHKhlnxS2zx7pHgOZQlQzy1fupPeB5t01Oza2f1+rjMO3muNOyozhtWJubE6hvYLwIY24ipFUMBvbn5FxRCliz2R0N5jcFCo3UMeVYQ6rf64/SdKJ1WMc40SI1eUfubufi7wgu2rK+PUY3TYXa3tH9EBuufTlE5GcZDNdMnffX09zURsQrUM1YxQJSDE4wims3j4okdARQl1El9exiA4848PeoE6nb2IQm3O7M8eHHOBvcpZdPWXeU=
  file_glob: true
  file: funz-calculator*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
