name: test

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 13]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    - if: matrix.os == 'macos-latest'
      run: |
        ln -s /Library/Frameworks/R.framework/Versions/3.6 /Library/Frameworks/R.framework/Versions/3.5
        echo "/Library/Frameworks/R.framework/Resources/bin" >> $GITHUB_PATH
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        pip install py4j==0.10.8.1
        pip install numpy
    - run: |
        WD=$PWD
        cd ..
        git clone https://github.com/Funz/funz-profile
        git clone https://github.com/Funz/funz-core
        cd funz-core
        ant clean dist
        cd ..
        git clone https://github.com/Funz/funz-client
        cd funz-client
        ANT_OPTS="-Xmx6G -Xss1G" ant clean dist-test
        cd ..
        cd $WD
      shell: bash
    - uses: GabrielBB/xvfb-action@v1
      with: 
        run: ant -noinput -buildfile build.xml clean test
      id: anttest
      continue-on-error: true
    - if: steps.anttest.outcome != 'success'
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ matrix.os }}-${{ matrix.java }}
        path: |
          *.txt
          *.log
    - if: matrix.os == 'ubuntu-latest' && steps.mvntest.outcome != 'success'
      run: sudo apt-get install imagemagick
    - if: steps.anttest.outcome != 'success'
      uses: OrbitalOwen/desktop-screenshot-action@0.1
      with:
        file-name: 'test-${{ matrix.os }}-${{ matrix.java }}.jpg'
    - run: ant -noinput -buildfile build.xml coverage
      if: matrix.os == 'ubuntu-latest'
    - uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
    - if: steps.anttest.outcome != 'success'
      run: exit 1
